version: '3.9'
services:
  api:
    container_name: digimon-api
    build:
      context: ./
      target: dev
    environment:
      NODE_ENV: dev
    env_file: .env_file
    depends_on:
      - db
    ports:
      - '3030:3030'
    networks:
      - api-service
    volumes:
      - ./:/app
    restart: always
  db:
    container_name: mongo
    image: mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
networks:
  api-service:
    driver: bridge
