version: '3.9'
services:
  api:
    container_name: digimon-api
    build:
      context: ./
      target: dev
    environment:
      NODE_ENV: dev
    env_file: .env
    depends_on:
      - mongo
    ports:
      - '3030:3030'
    volumes:
      - ./:/app
      - /app/node_modules/bcrypt/
    restart: always
  mongo:
    container_name: mongo-db
    image: mongo
    restart: always
    volumes:
      - digimon-service-data:/data/db
    ports:
      - 27017:27017
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
volumes:
  digimon-service-data:
