version: '3.9'
services:
  api:
    container_name: digimon-api
    build:
      context: ./
      target: dev
    environment:
      NODE_ENV: dev
    env_file: .env
    depends_on:
      - mongo
    ports:
      - '3030:3030'
    volumes:
      - ./:/app
    restart: always
  mongo:
    container_name: mongo-db
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    volumes:
      - /mongo-data:/data/db
    ports:
      - 27017:27017
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.6.0
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      discovery.type: single-node
      xpack.license.self_generated.type: trial
  kibana:
    container_name: kibana
    image: kibana:7.6.0
    depends_on:
      - elasticsearch
    ports:
      - '5601:5601'
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
